# Generated by Django 4.2.24 on 2025-09-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_product', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
