# Generated by Django 4.2.24 on 2025-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_gallery_product_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_text',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
