
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=buywithdts
      - POSTGRES_DB=db

  backend:
    build: ./backend
    container_name: dts_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

    environment:
      - VIRTUAL_HOST=api.shop-dts.org
      - LETSENCRYPT_HOST=api.shop-dts.org
      - LETSENCRYPT_EMAIL=shopdtsorg@gmail.com
    networks:
      - webnet

  front:
    build: "./frontend"
    container_name: dts_front
    ports:
      - "3000:80"

    
    environment:
      - VIRTUAL_HOST=shop-dts.org
      - LETSENCRYPT_HOST=shop-dts.org
      - LETSENCRYPT_EMAIL=shopdtsorg@gmail.com
    networks:
      - webnet

  admin:
    build: "./admin"
    container_name: dts_admin
    ports:
      - "3001:80"

    environment:
      - VIRTUAL_HOST=admin.shop-dts.org
      - LETSENCRYPT_HOST=admin.shop-dts.org
      - LETSENCRYPT_EMAIL=shopdtsorg@gmail.com
    networks:
      - webnet


  nginx:  
    image: jwilder/nginx-proxy
    container_name: nginx 
    restart: always 
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - front
      - admin
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html/front
      - ./admin/build:/usr/share/nginx/html/admin
      
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme.sh:/etc/acme.sh
    networks:
      - webnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/etc/nginx/html
      - ./acme.sh:/etc/acme.sh

    depends_on:
      - nginx
    networks:
      - webnet
    
networks:
  webnet: