version: "3.9"

services:
    db:
      image: postgres:15
      container_name: postgres_db
      restart: alway
      volumes:
        - ./db:/var/lib/postgresql/data 
      ports:
        - "5432:5432"
      env_file:
        - .env
       


    backend:
      build: ./backend
      container_name: dts_backend
      command: bash -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
      volumes:
        - ./backend:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
      env_file:
        - .env

    front:
      build: ./front
      container_name: dts_front
      ports:
        - "3000:80"
      depends_on:
        - backend

      env_file:
        - .env

    admin:
      build: ./admin
      container_name: dts_admin
      ports:
        - "3001:80"
      depends_on:
        - backend

      env_file:
        - .env


    
    nginx:
      build: ./nginx
      container_name: dts_nginx
      ports:
        - "80:80"
      depends_on:
        - front
        - admin
        - backend


  

     

    
