
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=buywithdts
      - POSTGRES_DB=db

  backend:
    build: ./backend
    container_name: dts_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  front:
    build: "./frontend"
    container_name: dts_front
    ports:
      - "3000:80"

  admin:
    build: "./admin"
    container_name: dts_admin
    ports:
      - "3001:80"

  nginx:  
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html/front
      - ./admin/build:/usr/share/nginx/html/admin
    ports: 
      - "80:80"
    depends_on:
      - front
      - admin
      - backend


