version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=buywithdts
      - POSTGRES_DB=db

  backend:
    build: ./backend
    container_name: dts_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env 

  front:
    build: "./frontend"
    container_name: dts_front
    ports:
      - "3000:80"

  admin:
    build: "./admin"
    container_name: dts_admin
    ports:
      - "3001:80"

  nginx:  
    build: "./nginx"
    container_name: dts_nginx
    ports: 
      - "80:80"
    depends_on:
      - front
      - admin
      - backend


