# Generated by Django 4.2.24 on 2025-09-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_gallery_product_alter_product_desc'),
        ('custom_auth', '0002_info_contact_number_alter_galleryevent_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bucket',
            field=models.ManyToManyField(to='custom_auth.orderitem'),
        ),
    ]
