# Generated by Django 4.2.24 on 2025-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_remove_profile_bucket_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='mbank_numbers',
        ),
        migrations.AddField(
            model_name='info',
            name='gmail',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='instagramm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='telegramm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
