# Generated by Django 4.2.24 on 2025-09-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_remove_info_mbank_numbers_info_gmail_info_instagramm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cheque',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='products',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
