# Generated by Django 4.2.24 on 2025-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_alter_cheque_id_alter_event_date_start_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='products',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(default=list),
        ),
    ]
