# Generated by Django 4.2.24 on 2025-10-24 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_cheque_client_number_order_cashier_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
